name: binder_env
channels:
- defaults
dependencies:
- pandas
- python=3.6.8
- pip
- tensorflow=2.4.0
- opencv
- pip:
  - tensorflow==1.11.0
  - keras==2.2.4
  - astropy
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - opencv-python 
