name: binder_env
channels:
- defaults
dependencies:
- python=3.6
- pip
- pip:
  - tensorflow==1.11.0
  - keras==2.2.4
  - numpy==1.19.1
  - scikit-image==0.17.2
  - matplotlib==3.3.4
  - opencv-python==4.5.3
  - astropy==4.1